/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package inferenciadedatos;

/**
 *
 * @author Abiu Franco
 */
public class InferenciaDatos extends javax.swing.JFrame {

    /**
     * Creates new form InferenciaDatos
     */
    public InferenciaDatos() {
        initComponents();
    }
    public boolean esBooleano(String dato){
        if(dato.equals("false")|| dato.equals("true")){
            return true;
        }
        return false;
    }
    public boolean esChar(String dato){
        if(dato.length()==1&& dato.charAt(0)!='ñ'){
            return true;
        }
        return false;
    }
    public boolean esByte(String dato){
        boolean isByte =  dato.matches("[+-]?\\d*?");
        if(isByte){ // ya tenemos numeros, validar rango
            int numero=Integer.parseInt(dato);
            if(numero>=-127&&numero<=128){
                return true;
            }
        }
        return false;
    }
    public boolean esShort(String dato){
        boolean isShort =  dato.matches("[+-]?\\d*?");
        if(isShort){ // ya tenemos numeros, validar rango
            int numero=Integer.parseInt(dato);
            if(numero>=-32768&&numero<=32767){
                return true;
            }
        }
        return false;
    }
    public boolean esEntero(String dato){
        boolean isNumeric =  dato.matches("[+-]?\\d*?");
        
        if(isNumeric){ // ya tenemos numeros, validar rango
            int numero=Integer.parseInt(dato);
            if(numero>=-2147483647&&numero<=2147483647){
                return true;
            }
        }
        return false;
    }
    public boolean esLong(String dato){
        boolean isLong =  dato.matches("[+-]?\\d*?");
        long inicio=-9223372036854775808L;
        long fin=9223372036854775807L;
        if (isLong) { // ya tenemos numeros, validar rango
            Integer numero = Integer.parseInt(dato);
            if (numero >= inicio  && numero <= fin) {
                return true;
            }
        }
        return false;
    }

    public boolean esFloat(String dato) {
        boolean isDouble = dato.matches("[+-]?\\d*\\.\\d+");
        if (isDouble) {
            if (dato.length() <= 10) {
                return true;
            }
        }
        return false;
    }

    public boolean esDouble(String dato) {
        boolean isDouble = dato.matches("[+-]?\\d*\\.\\d+");
        return isDouble;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        txt_dato = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        lbl_tipoDato = new javax.swing.JLabel();
        btn_infeririDato = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(102, 102, 102));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("INGRESE EL DATO");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 10, -1, -1));
        jPanel1.add(txt_dato, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 50, 140, -1));

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("DATO");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 50, 60, 20));

        lbl_tipoDato.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        lbl_tipoDato.setForeground(new java.awt.Color(255, 255, 255));
        lbl_tipoDato.setText("El tipo de dato es: ");
        jPanel1.add(lbl_tipoDato, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 120, 380, -1));

        btn_infeririDato.setText("Inferir Dato");
        btn_infeririDato.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_infeririDatoActionPerformed(evt);
            }
        });
        jPanel1.add(btn_infeririDato, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 170, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 415, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 264, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_infeririDatoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_infeririDatoActionPerformed
        lbl_tipoDato.setText("El tipo de dato es: ");
        String dato = txt_dato.getText();
        if(txt_dato.getText().length()<7){
        if (esBooleano(dato)) {
            lbl_tipoDato.setText(lbl_tipoDato.getText()+" boolean ");
            //System.out.println("El dato ingresado es de tipo boolean");
        }
        if (esChar(dato)) {
            lbl_tipoDato.setText(lbl_tipoDato.getText()+" char ");
            //System.out.println("El dato ingresado es de tipo char");
        }
        if (esByte(dato)) {
            lbl_tipoDato.setText(lbl_tipoDato.getText()+" byte ");
            //System.out.println("El dato ingresado es de tipo byte");
        }
        if (esShort(dato)) {
            lbl_tipoDato.setText(lbl_tipoDato.getText()+" short ");
            //System.out.println("El dato ingresado es de tipo short");
        }
        if (esEntero(dato)) {
            lbl_tipoDato.setText(lbl_tipoDato.getText() + " entero ");
            //System.out.println("El dato ingresado es de tipo entero");
        }}
        if (esLong(dato)) {
            lbl_tipoDato.setText(lbl_tipoDato.getText() + " long ");
            //System.out.println("El dato ingresado es de tipo entero");
        }
        if (esFloat(dato)) {
            lbl_tipoDato.setText(lbl_tipoDato.getText()+" float ");
            //System.out.println("El dato ingresado es de tipo Float");
        }
        if (esDouble(dato)) {
            lbl_tipoDato.setText(lbl_tipoDato.getText()+" double ");
            //System.out.println("El dato ingresado es de tipo double");
        }

        //System.out.println("-----------------------******---------------------");
    }//GEN-LAST:event_btn_infeririDatoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(InferenciaDatos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(InferenciaDatos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(InferenciaDatos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(InferenciaDatos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new InferenciaDatos().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_infeririDato;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lbl_tipoDato;
    private javax.swing.JTextField txt_dato;
    // End of variables declaration//GEN-END:variables
}
